#!/usr/bin/env php
<?php
declare(strict_types=1);

// check for pdepend installed as composer package
if (file_exists(__DIR__ . '/../../../autoload.php')) {
    include __DIR__ . '/../../../autoload.php';
} else {
    include __DIR__ . '/../vendor/autoload.php';
}

use Symfony\Component\Console\Application;
use Versioning\Console\IncrementConsole;
use Versioning\Console\InitializeConsole;

use League\Flysystem\Filesystem;
use League\Flysystem\Adapter\Local;

$adapter = new Local('.');
$filesystem = new Filesystem($adapter);

$application = new Application();
$application->add(new InitializeConsole($filesystem));
$application->add(new IncrementConsole($filesystem));
$application->run();
